### ISSUE TITLE
ESLint 6

### ISSUE THREAD

**Issue by b-my** [archived-codacy/codacy-eslint-legacy#137]
We are migrating our application to typescript. For a while we will have a mixed codebase of javascript and typescript. We would like to lint both types of file in the same way. To do this we would use the `overrides` -> `extends` functionality in the `.eslintrc` something like this:
```
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"],
      "parser": "@typescript-eslint/parser",
      "plugins": ["@typescript-eslint"],
      "extends": [
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "prettier/@typescript-eslint"
      ],
     ...
```
This functionality only works correctly in eslint 6+ ([issue here](https://github.com/eslint/eslint/pull/11554)). Are there plans to update the version of eslint used here to version 6? Can I submit a PR to do this?

**Comment by lolgab** [comment]
Hi @b-my, 
We did update ESLint right before the new version 6 was released.
We are very interested on updating it but, it's not the first tool to update in out schedule.
PRs are welcome, but, being it a major version upgrade, we will have to test it throughly before merging to be sure it doesn't affect existing users.

**Comment by b-my** [comment]
I have managed to find a workaround using the current version of eslint. For anyone experiencing a similar problem I used [this](https://github.com/eslint/eslint/issues/8813#issuecomment-456034732) suggestion.
