### ISSUE TITLE
Used packages versions are incompatible

### ISSUE THREAD

**Issue by bsekachev** [archived-codacy/codacy-eslint-legacy#153]
Hello,
 
I come across some issues with codacy-eslint.
In our project we use airbnb rules preset for typescript:

```
'extends': [
    'airbnb-typescript',
],
```

Locally eslint works well and I do not get any warnings. But in our github repos we use codacy to CI. And here we get some warnings like: ``Definition for rule '...' was not found``

As I can see, your built script  ```build.sbt``` installs a lot of packages with specific versions. 
It installs for example ``eslint-config-airbnb-typescript@6.0.0`` which requires ``@typescript-eslint/eslint-plugin@^2.3.0``.  

But ``build.sbt`` installs only ``@typescript-eslint/eslint-plugin@1.9.0`` and this version of the package 
doesn't consist some rules which are needed in ``eslint-config-airbnb-typescript@6.0.0``. 

For example: 
- ``@typescript-eslint/no-empty-function``
- ``@typescript-eslint/quotes``
- ``@typescript-eslint/brace-style``
And probably others. 

We also have similar issues between ``slint-config-airbnb-typescript`` and ``eslint-plugin-react`` packages (rule: ``react/jsx-curly-newline``)

What should we do to cope with it?

**Comment by mrfyda** [comment]
hey @bsekachev

we recently updated eslint and most plugins a major version.
this issue should now be fixed as we updated `eslint-config-airbnb-typescript` to 6.3.1.

if you are still experiencing this issue please reopen it!
