### ISSUE TITLE
[enhancement] Allow to add Plugin js to ESLint engine

### ISSUE THREAD

**Issue by rsoesemann** [archived-codacy/codacy-eslint-legacy#55]
This issue was created after a Skyoe chat with @rtfpessoa. 

Salesforce.com has a new UI technology called Lightning which heavily relies on Javascript. To check code style and security Salesforce provide a so called [Lightning CLI](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/cli_intro.htm) based on Heroku CLI. For its checks it uses [ESLint plus custom rules/plugins](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/cli_rules.htm).

Salesforce.com developers who want to continously check their code using Codacy.com now have a problem. They have to run the local Lightning CLI and Codacy.com ESLint to check their code.

The goal of this issue is to find out if the CLI rules and plugins are in a way integratable into Codacy.

**Comment by rtfpessoa** [comment]
@up2go-rsoesemann do you have any extra insights about this? I have not found any way to achieve this. Does this still make sense?

**Comment by rsoesemann** [comment]
Not really. I just close it.
