### ISSUE TITLE
Receiving errors for resolving webpack

### ISSUE THREAD

**Issue by chrisjbrown** [archived-codacy/codacy-eslint-legacy#56]
Receiving these errors on codacy but not locally

`Resolve error: Cannot find module 'webpack' (import/no-extraneous-dependencies)`

on lines like

`import 'whatwg-fetch';`

here is my .eslintrc

```{
  "parser": "babel-eslint",
  "cache": true,
  "env": {
    "browser": true,     // browser global variables.
    "node": true,        // Node.js global variables and Node.js-specific rules.
    "es6": true,
    "jasmine": true     // adds all of the Jasmine testing global variables for version 1.3 and 2.0.
  },
  "globals": {
    "__ENV__": true,
    "__DROPSHIPPER_API__": true,
    "__CATALOG_API__": true,
    "__VERSION_NPM__": true,
    "__VERSION_GIT__": true,
    "__TEST__": true,
    "Bugsnag": true
  },
  "plugins": [
    "import"
  ],
  "extends": [
    "airbnb",
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  "rules": {
    "import/no-unresolved": [1],
    "import/extensions": [0],
    "import/default": [0],
    "import/prefer-default-export": [0],
    "no-constant-condition": [0],
    "no-param-reassign": [0],
    "react/jsx-filename-extension": [0],
    "react/prefer-stateless-function": [2, { "ignorePureComponents": true }],
    "react/jsx-closing-bracket-location": [0],
    "react/jsx-boolean-value": [0],
    "class-methods-use-this": [0],
    "no-class-assign": [0]
  },
  "settings": {
    "import/resolver": "webpack"
  }
}
```

**Comment by rtfpessoa** [comment]
Codacy does not run npm install on the projects it analyses due to security reasons. The probable cause of this error is that the folder node_modules does not exist when Codacy is running ESLint on the project.

**Comment by chrisjbrown** [comment]
Is there a best practice for this to avoid having a errors on all of my import statements?

**Comment by rtfpessoa** [comment]
Currently we already remove some from the output here https://github.com/codacy/codacy-eslint/blob/master/src/main/scala/codacy/eslint/ESLint.scala#L16

Maybe you can add more ids of the patterns you are receiving.

**Comment by chrisjbrown** [comment]
opened a [PR](https://github.com/codacy/codacy-eslint/pull/57) for excluding these rules

**Comment by rtfpessoa** [comment]
We will release this as soon as possible to production.

**Comment by chrisjbrown** [comment]
Thanks!
