### ISSUE TITLE
Update Prettier to latest version

### ISSUE THREAD

**Issue by mikbry** [archived-codacy/codacy-eslint-legacy#88]
We are using Prettier 1.9 to add `arrowParens` option. But codacy-eslint is locked to Prettier 1.7, which don't support it. So Codacy fail to check correctly our repos. 

See:
https://github.com/Opla/front/issues/65

**Comment by rtfpessoa** [comment]
You can send a PR updating the three plugins here: https://github.com/codacy/codacy-eslint/blob/master/build.sbt#L75 and we will proceed with the update.

**Comment by mikbry** [comment]
It works, great !
