### ISSUE TITLE
Parameters for the 'Require IIFEs to be Wrapped' rule

### ISSUE THREAD

**Issue by asvanberg** [archived-codacy/codacy-eslint-legacy#9]
Allow use to specify how we want them to be wrapped as per http://eslint.org/docs/rules/wrap-iife

**Comment by machadoit** [comment]
Thank you for letting us know, we do have some missing parameters, it will be done when we deploy the changes in https://github.com/codacy/codacy-eslint/pull/10

Feel free to ask for other missing parameters or you can do a PR yourself like the one above =)
